apiVersion: v1
kind: Namespace
metadata:
  name: falco-demo
---
apiVersion: v1
kind: Pod
metadata:
  name: vulnerable-demo
  namespace: falco-demo
spec:
  containers:
  - name: demo
    image: alpine:3.22
    command: ["/bin/sh","-c"]
    args:
    - |
      echo 'root:x:0:0:root:/root:/bin/ash' > /tmp/passwd
      echo 'root:demo:20000:0:99999:7:::' > /tmp/shadow
      cp /tmp/passwd /etc/passwd
      cp /tmp/shadow /etc/shadow
      chmod 640 /etc/shadow
      sleep infinity
    securityContext:
      runAsUser: 0
      allowPrivilegeEscalation: false
    resources:
      requests: {cpu: 5m, memory: 8Mi}
      limits: {cpu: 100m, memory: 32Mi}
